# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [
    "modprobe.blacklist=sp5100_tco" # watchdog for AMD
  ];

  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/nvme1n1p4";
    fsType = "btrfs";
		options = [ "subvol=@" ];
  };

  fileSystems."/boot" = {
    device = "/dev/nvme1n1p3";
    fsType = "vfat";
  };

  fileSystems."/media/dev" = {
    device = "/dev/nvme2n1p1";
    fsType = "ntfs";
  };

  fileSystems."/media/hdd" = {
    device = "/dev/sda2";
    fsType = "ntfs";
  };

  fileSystems."/media/data" = {
    device = "/dev/nvme0n1p2";
    fsType = "exfat";
  };
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = "performance";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
