{ pkgs, config, ... }:

let inherit (import ./variables.nix) username gitUsername;
in {
  users.mutableUsers = false;
  programs.fish.enable = true;
  users.defaultUserShell = pkgs.fish;
  environment.shells = with pkgs; [ bashInteractive fish nushell ];

  users.groups = {
    "${username}" = { };
    docker = { };
    # for android platform tools's udev rules
    adbusers = { };
    dialout = { };
    # misc
    uinput = { };
  };

  users.users."${username}" = {
    # generated by `mkpasswd -m scrypt`
    # we have to use initialHashedPassword here when using tmpfs for /
    initialHashedPassword =
      "$7$CU..../....ZimUYbCXIwOK4usy/v1cb0$ReWD4cqEGplIPmKWA/fI0FDLkQdgLIN6NQqx.HMuqU3";
    home = "/home/${username}";
    homeMode = "755";
    isNormalUser = true;
    description = "${gitUsername}";
    extraGroups = [
      username
      "users"
      "networkmanager"
      "wheel"
      "docker"
      "adbusers"
      "libvirtd"
      "scanner"
      "lp"
      "video"
      "input"
      "audio"
    ];
  };

  # root's ssh key are mainly used for remote deployment
  users.users.root = {
    initialHashedPassword =
      config.users.users."${username}".initialHashedPassword;
    openssh.authorizedKeys.keys =
      config.users.users."${username}".openssh.authorizedKeys.keys;
  };
}

